### ISSUE TITLE
harness: per-repo Python version mapping for datasci-mini set

### ISSUE THREAD

**Issue by hyang0129** [hyang0129/onlycodes#202]
## Background

The datasci-mini batch (D1–D5, 50 problems) includes old scikit-learn versions (0.20, 0.21, 0.22) that fail to compile under Python 3.11 due to two compounding issues:

1. **setuptools ≥ 61** rejects the old flat-layout package discovery (sklearn + build_tools as co-top-level packages)
2. **Cython 0.29.x** hits a signature mismatch in `quad_tree.pxd` vs `quad_tree.pyx` for scikit-learn 0.20/0.21

The harness currently hardcodes `python3.11` for all venvs (`harness.py:361`). Python 3.10 with `setuptools<60`, `numpy<1.24`, `cython<3` installs scikit-learn 0.20 cleanly (verified).

## Why this matters for both arms

The harness injects the venv python path into the agent system prompt (`run.py:199`):

```
The project's Python interpreter and dependencies are pre-installed at: /tmp/swebench/venvs/<id>/bin/python
```

The onlycode agent uses that exact binary via `codebox.run()` for test verification. A broken venv means:
- test grading always fails (harness can't run tests)
- onlycode agent is flying blind (all its test-verification calls fail too)

## Proposed implementation

Add a repo-keyed Python version map in `harness.py`:

```python
_REPO_PYTHON = {
    "scikit-learn/scikit-learn": "python3.10",
    "matplotlib/matplotlib": "python3.10",
    "pydata/xarray": "python3.10",
    "mwaskom/seaborn": "python3.10",
}
_DEFAULT_PYTHON = "python3.11"
```

Change `setup_venv(venv_dir, repo_dir)` to accept an optional `python_bin` parameter, defaulting via a lookup on the repo name derived from the path or passed in from `run.py`.

Also add pre-install pins for repos that need them:

```python
_REPO_PRE_INSTALL = {
    "scikit-learn/scikit-learn": ["setuptools<60", "numpy<1.24", "cython<3"],
}
```

These pins run before `pip install -e .` using `--no-build-isolation`.

## Affected instances

All D1–D5 scikit-learn instances (15 total):
- **0.20** (5): 10427, 10803, 11206, 11596, 3840
- **0.21** (3): 12704, 13283, 13496
- **0.22** (5): 13013, 13864, 14125, 14710, 15094
- **1.3** (2): 24677, 25694 — work on both 3.10 and 3.11, no change needed

matplotlib (12), xarray (8), seaborn (5) instances should also benefit from Python 3.10 (all are 2019–2022 era).

## Out of scope

- The codebox kernel itself always uses system `python3` (3.12) for the kernel process itself; this is intentional and not changed. Only the test-execution subprocess path changes.
- Django and Sphinx (V1–V4, already complete) are unaffected — their venvs were already built and results recorded.

**Comment by hyang0129** [comment]
## Sanity-check findings

Seven potential issues investigated against the current code. Summary below with exact file references.

---

### Issue 1 — Call site coverage: less bad than it looks

Both `setup_venv()` call sites ([run.py:359](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/run.py#L359), [run.py:413](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/run.py#L413)) have the full `Problem` object in scope, so `problem.repo_slug` is available at both. Threading `python_bin` is straightforward.

The `reinstall_editable()` path at [run.py:184](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/run.py#L184) runs `pip install --no-deps -e .` — `--no-deps` still triggers C extension compilation. But once the venv has `cython<3` installed from initial setup, subsequent `--no-deps` calls use the venv's Cython, so this is self-healing after correct first-time setup.

### Issue 2 — Existing venv early-return: confirmed, needs a fix

No version sentinel exists. Detection is purely directory-based ([harness.py:317–359](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/harness.py)):

```python
if os.path.isdir(venv_dir):
    if not os.path.isfile(pip):
        shutil.rmtree(...)
    else:
        ...
        return  # ← early return; python version never checked
```

Any existing 3.11 venv for scikit-learn instances silently persists. The proposed change would be inert on reruns. **Fix: write a sentinel file `venv/.python_bin` on venv creation; if missing or mismatched, wipe and recreate.**

### Issue 3 — Pre-install pins in existing-venv path: mitigated

The early-return path runs `pip install --quiet --no-deps -e .` which does recompile C extensions (comment at [harness.py:325](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/harness.py#L325) confirms this). However, if the venv was initially created with the pinned `cython<3`, the recompilation will use that pinned Cython. Only bites on first setup of a broken 3.11 venv — which the sentinel fix in Issue 2 handles by forcing a rebuild.

### Issue 4 — reinstall_editable: not blocking

`reinstall_editable()` ([cache.py:221](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/cache.py#L221)) uses `--no-deps`. After a correct initial setup the venv's `cython<3` handles any recompilation. Not a blocking issue.

### Issue 5 — matplotlib/xarray/seaborn: unverified claim

Nothing in the codebase substantiates why these repos fail on 3.11. The only matplotlib mention ([harness.py:~64](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/harness.py#L64)) is about `.so` path retention after `git clean`, not compilation failure. No xarray or seaborn mentions at all.

The established pattern is `_needs_jinja2_pin()` ([harness.py:279](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/harness.py#L279)): detect via source-file grep, then pin. The proposal skips that step for these three repos. **Recommend deferring matplotlib/xarray/seaborn until there is actual failure data; blanket-mapping 25 instances to 3.10 on a hunch risks introducing new failures.**

### Issue 6 — --no-build-isolation scope: needs explicit scoping

None of the three pip install sites ([harness.py:330](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/harness.py#L330), [harness.py:374](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/harness.py#L374), [cache.py:235](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/cache.py#L235)) currently use `--no-build-isolation`. The fix must add it **only** to the fresh-venv main install when `pre_install` pins are present:

```python
if pre_install:
    subprocess.run([pip, "install", *pre_install], ...)
    subprocess.run([pip, "install", "-e", repo_dir, "--no-build-isolation"], ...)
else:
    subprocess.run([pip, "install", "-e", repo_dir], ...)  # unchanged
```

Never add `--no-build-isolation` to the existing-venv path or `reinstall_editable` — adding it globally would break repos that rely on pip's build isolation.

### Issue 7 — Cache invalidation: addressable without code changes

The lockfile is sorted `pip freeze` output ([cache.py:172](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/cache.py#L172)). Deleting a cache entry's `lockfile.txt` triggers the rebuild path in `_setup_problem_cached()` ([run.py:400](https://github.com/hyang0129/onlycodes/blob/main/onlycodes/swebench/run.py#L400)) automatically. For the 13 affected scikit-learn instances a one-shot shell script handles this — no code change needed for the cache path:

```bash
for id in 10427 10803 11206 11596 3840 12704 13283 13496 13013 13864 14125 14710 15094; do
    rm -f "${SWEBENCH_CACHE_ROOT}/instances/scikit-learn__scikit-learn-${id}/lockfile.txt"
done
```

---

## Recommended implementation

Three code changes + one script, replacing the original proposal:

1. **Version sentinel** — write `venv/.python_bin` on creation; wipe-and-rebuild if missing or mismatched at start of `setup_venv()`
2. **Thread `python_bin`** — add lookup helper `_python_for(repo_slug)` in `run.py`; both call sites already have `problem.repo_slug`; `setup_venv()` gains an optional `python_bin` param
3. **Scoped `--no-build-isolation`** — only when `pre_install` list is non-empty, only on the fresh-venv install path
4. **Cache-bust script** — delete lockfiles for the 13 scikit-learn instances before the first datascience run

Scope: scikit-learn 15 instances only. Defer matplotlib/xarray/seaborn until failure data exists. A new implementation issue is being filed.

**Comment by hyang0129** [comment]
## Failure-data follow-up: matplotlib / xarray / seaborn

Ran fresh install probes on the earliest instance from each of the three repos: clone at `base_commit`, `python3.11 -m venv`, `pip install setuptools wheel`, `pip install -e .` (mirroring the harness fresh-venv path exactly).

| Instance | base_commit | Python 3.11 result |
|---|---|---|
| `pydata__xarray-2905` | 7c4e2ac8 | ✅ **exit 0** |
| `mwaskom__seaborn-2389` | bcdac541 | ✅ **exit 0** |
| `matplotlib__matplotlib-13859` | acad890a (2019, matplotlib 3.1) | ❌ exit 1 |

### xarray and seaborn

Both install cleanly on Python 3.11 with the existing harness flow. **No change needed** — the original hypothesis was wrong for these two.

### matplotlib failure: NOT a Python version issue

Two distinct root causes from the failure log:

**1. Missing system FreeType headers**

```
src/checkdep_freetype2.c:1:10: fatal error: ft2build.h: No such file or directory
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

`libfreetype6` is installed in the container but `libfreetype6-dev` (which provides `ft2build.h`) is not. matplotlib's setup.py tries to compile against system FreeType.

**2. numpy 2.x ABI break**

```
Collecting numpy>=1.11 (from matplotlib==0+untagged.1.gacad890)
  Using cached numpy-2.4.4-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
```

matplotlib 3.1 (2019) was built against numpy 1.x ABI. Pip's unconstrained `numpy>=1.11` resolves to 2.4.4, which breaks at C extension load time.

**Switching to Python 3.10 would fix neither of these.** Python 3.10 also lacks `ft2build.h` if the dev package isn't installed, and would still resolve numpy to 2.4.4.

### Verified fix (still on Python 3.11)

```bash
sudo apt-get install -y libfreetype6-dev libpng-dev pkg-config
```

then in the venv:
```bash
pip install "setuptools<65" wheel "numpy<2" "cython<3"
pip install -e . --no-build-isolation
```

Tested end-to-end: **exit 0, matplotlib 3.1 installs cleanly on Python 3.11.**

---

## Revised scope

| Repo | Original proposal | Verified action |
|---|---|---|
| scikit-learn | python3.10 + setuptools<60, numpy<1.24, cython<3 | unchanged — same prescription |
| matplotlib | python3.10 + (no pins listed) | **Python 3.11 unchanged**; add system deps to Dockerfile; venv pin `numpy<2`, `setuptools<65`, `cython<3` |
| xarray | python3.10 | **no change** — works on 3.11 |
| seaborn | python3.10 | **no change** — works on 3.11 |

The system-deps part (libfreetype6-dev, libpng-dev, pkg-config) belongs in the devcontainer image, not the harness. Spec #203 will be updated to:
1. Keep the scikit-learn fix as-is (python3.10 + pre_install pins)
2. Add a matplotlib pre_install entry: `["numpy<2", "setuptools<65", "cython<3"]` — Python version unchanged
3. Add a separate Dockerfile / devcontainer task for the system deps
4. Drop xarray and seaborn from any mapping

**Comment by hyang0129** [comment]
## Final sweep: sympy + astropy + late matplotlib

Probed 3 more instances (sympy-11232, astropy-6938, matplotlib-26160 latest), plus the 2 remaining astropy instances after the first failed, plus a critical re-test of matplotlib-13859 with libfreetype6-dev now installed at system level.

### Results

| Instance | Era | Install on 3.11 | Import works? | Notes |
|---|---|---|---|---|
| `sympy-11232` | 2016 | ✅ exit 0 | (pure Python, fine) | no change |
| `xarray-2905` | 2019 | ✅ exit 0 | (verified earlier) | no change |
| `seaborn-2389` | 2021 | ✅ exit 0 | (verified earlier) | no change |
| `matplotlib-13859` (3.1) | 2019 | ✅ with libfreetype6-dev | ❌ `numpy.core.multiarray failed to import` | needs `numpy<2` pin |
| `matplotlib-26160` (3.7) | 2023 | ✅ | ✅ | no pins needed |
| `astropy-6938` (3.x) | 2018 | ❌ | — | needs Python 3.9 (`collections.MutableSequence` removed in 3.10) — **not installed in container** |
| `astropy-12962` (5.x) | 2022 | ❌ | — | needs `setuptools<69` + `numpy<2` + `cython<3` + `extension-helpers` |
| `astropy-13842` (5.x) | 2022 | ❌ | — | same — verified fix exit 0 |

### Three new findings

**1. Install success ≠ working venv.**

matplotlib-13859 `pip install -e .` returns exit 0 even when its C extensions were silently compiled against numpy 2.x ABI. The breakage only surfaces on `import matplotlib.pyplot`:

```
ImportError: numpy.core.multiarray failed to import
```

Every harness probe should add a smoke-import check (`python -c "import <module>"`) before declaring a venv healthy. The current harness has no such check.

**2. Per-repo pins are too coarse — matplotlib needs per-version logic.**

- matplotlib 3.1 (2019, instance 13859): **needs** `numpy<2` pin
- matplotlib 3.7 (2023, instance 26160): **must not** have `numpy<2` pin — its modern features depend on newer numpy

A single `_REPO_PRE_INSTALL["matplotlib/matplotlib"]` map applies pins to all 12 instances. Apply `numpy<2` blindly and you'll break the 5–6 newer ones; omit it and the 6–7 older ones import-fail. **The data model needs to be instance-keyed, or version-range-keyed**, not just repo-keyed.

**3. astropy-6938 is currently un-runnable.**

The container has Python 3.10, 3.11, 3.12 — but no 3.9. astropy 3.x (2018) imports `collections.MutableSequence`, which was removed in Python 3.10. Three options:

  - **(a)** Add `python3.9` to the devcontainer image (`apt install python3.9 python3.9-venv` from deadsnakes PPA). Cleanest.
  - **(b)** Drop astropy-6938 from datasci-mini. Acceptable if 2 of 3 astropy instances suffice for the benchmark.
  - **(c)** Monkey-patch `collections` to alias from `collections.abc` via a `sitecustomize.py` in the venv. Fragile; affects everything in that venv.

Recommend (a) — same approach already taken for python3.10.

### Verified astropy 5.x fix

```bash
.venv/bin/pip install "setuptools<69" wheel "numpy<2" "cython<3" extension-helpers
.venv/bin/pip install -e . --no-build-isolation
```
Exit 0 on both astropy-12962 and astropy-13842. `extension-helpers` is the build-time dependency that older astropy_helpers used to bundle but newer astropy doesn't.

### Revised picture

| Repo | Action |
|---|---|
| scikit-learn | python3.10 + `setuptools<60, numpy<1.24, cython<3` (unchanged) |
| matplotlib (3.1 era) | python3.11 + `numpy<2, setuptools<65, cython<3` |
| matplotlib (3.5+) | python3.11 + no pins |
| astropy 3.x (6938) | needs python3.9 in container, or drop instance |
| astropy 5.x (12962, 13842) | python3.11 + `setuptools<69, numpy<2, cython<3, extension-helpers` |
| xarray, seaborn, sympy | no change |

### Implications for spec #203

The repo-keyed lookup tables in #203 are not granular enough. Two changes needed:

1. **Instance-level overrides**: a third map keyed by `instance_id` that overrides the repo-level entry. matplotlib-13859 gets `numpy<2`; matplotlib-26160 inherits the repo default (empty).
2. **Post-install smoke import**: after `setup_venv()` returns, run `venv/bin/python -c "import <toplevel>"`. If that fails, treat as a setup failure rather than running the agent against a silently-broken venv.

I'll revise #203 with these changes and the astropy 3.9-or-drop decision.

**Comment by hyang0129** [comment]
Harness-quality improvement not needed post-submission -- paper numbers already generated under the corrected harness. Closing as not pursued post-submission.
